version: "3.8"

services:
  app:
    image: node:lts-alpine3.10
    command: sh -c "npm install && cd client/ && npm install && cd ../ && npm run start:dev"
    ports:
      - 3000:3000
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app

  mongo:
    image: mongo
    volumes:
      - st-premium-mongo:/data/db
    ports:
      - 27017:27017

volumes:
  st-premium-mongo:
