version: "3.8"

services:
  server:
    image: node:current-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./server:/app

  client:
    image: node:lts-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./client:/app

  mongo:
    image: mongo
    volumes:
      - st-premium-mongo:/data/db
    ports:
      - 27017:27017

volumes:
  st-premium-mongo:
