version: "3.8"

services:
  server:
    build: ./server
    restart: always

  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - st-premium-mongo:/data/db
    restart: always

  scrape:
    image: node:current-buster
    command: sh -c "npm install -g typescript && npm install && npm run prod"
    working_dir: /scrape
    volumes:
      - ./scrape:/scrape
    restart: always

volumes:
  st-premium-mongo:
