version: "3.8"

services:
  server:
    build: ./server
    restart: always

  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - st-premium-mongo:/data/db
    restart: always

  scrape:
    build: ./scrape

volumes:
  st-premium-mongo:
